---
- name: include variable overrides
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
        - "vars/main.yml"

- name: install nfs client packages
  package:
    name: "{{ item }}"
    state: "{{ nfs_packages_state }}"
  with_items: "{{ nfs_packages_client | default(nfs_packages_client_default) }}"

- name: install nfs server packages
  package:
    name: "{{ item }}"
    state: "{{ nfs_packages_state }}"
  with_items: "{{ nfs_packages_server | default(nfs_packages_server_default) }}"
  when: nfs_server

- name: create nfs export directories
  file:
    path: "{{ item.strip().split()[0] }}"
    state: directory
  with_items: "{{ nfs_exports }}"
  when: nfs_server
  notify: restart nfs

- name: configure nfs exports
  template:
    src: "{{ nfs_conf_template }}"
    dest: "{{ nfs_conf_path }}"
  vars:
    exports: "{{ nfs_exports }}"
  when: nfs_server
  notify: restart nfs

- name: manage nfs server services
  service:
    name: "{{ item }}"
    state: "{{ nfs_service_status }}"
    enabled: "{{ nfs_service_enabled }}"
  with_items: "{{ nfs_service_names | default(nfs_service_names_default) }}"
  when: nfs_server

- name: manage nfs client services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ nfs_client_services }}"
  when: nfs_client_services is defined
